import '../../domain/domain.dart';
import '../model/breeds_response.dart';

class BreedResponseMapper implements Mapper<BreedResponse> {

  @override
  BreedResponse fromMap(Map<String, dynamic> json) => BreedResponse(
    weight: Weight.fromJson(json["weight"]),
    id: json["id"],
    name: json["name"],
    cfaUrl: json["cfa_url"],
    vetstreetUrl: json["vetstreet_url"],
    vcahospitalsUrl: json["vcahospitals_url"],
    temperament: json["temperament"],
    origin: json["origin"],
    countryCodes: json["country_codes"],
    countryCode: json["country_code"],
    description: json["description"],
    lifeSpan: json["life_span"],
    indoor: json["indoor"],
    lap: json["lap"],
    altNames: json["alt_names"],
    adaptability: json["adaptability"],
    affectionLevel: json["affection_level"],
    childFriendly: json["child_friendly"],
    dogFriendly: json["dog_friendly"],
    energyLevel: json["energy_level"],
    grooming: json["grooming"],
    healthIssues: json["health_issues"],
    intelligence: json["intelligence"],
    sheddingLevel: json["shedding_level"],
    socialNeeds: json["social_needs"],
    strangerFriendly: json["stranger_friendly"],
    vocalisation: json["vocalisation"],
    experimental: json["experimental"],
    hairless: json["hairless"],
    natural: json["natural"],
    rare: json["rare"],
    rex: json["rex"],
    suppressedTail: json["suppressed_tail"],
    shortLegs: json["short_legs"],
    wikipediaUrl: json["wikipedia_url"],
    hypoallergenic: json["hypoallergenic"],
    referenceImageId: json["reference_image_id"],
    catFriendly: json["cat_friendly"],
    bidability: json["bidability"],
  );

  @override
  Map<String, dynamic>? toMap(BreedResponse data) => {
    "weight": data.weight.toJson(),
    "id": data.id,
    "name": data.name,
    "cfa_url": data.cfaUrl,
    "vetstreet_url": data.vetstreetUrl,
    "vcahospitals_url": data.vcahospitalsUrl,
    "temperament": data.temperament,
    "origin": data.origin,
    "country_codes": data.countryCodes,
    "country_code": data.countryCode,
    "description": data.description,
    "life_span": data.lifeSpan,
    "indoor": data.indoor,
    "lap": data.lap,
    "alt_names": data.altNames,
    "adaptability": data.adaptability,
    "affection_level": data.affectionLevel,
    "child_friendly": data.childFriendly,
    "dog_friendly": data.dogFriendly,
    "energy_level": data.energyLevel,
    "grooming": data.grooming,
    "health_issues": data.healthIssues,
    "intelligence": data.intelligence,
    "shedding_level": data.sheddingLevel,
    "social_needs": data.socialNeeds,
    "stranger_friendly": data.strangerFriendly,
    "vocalisation": data.vocalisation,
    "experimental": data.experimental,
    "hairless": data.hairless,
    "natural": data.natural,
    "rare": data.rare,
    "rex": data.rex,
    "suppressed_tail": data.suppressedTail,
    "short_legs": data.shortLegs,
    "wikipedia_url": data.wikipediaUrl,
    "hypoallergenic": data.hypoallergenic,
    "reference_image_id": data.referenceImageId,
    "cat_friendly": data.catFriendly,
    "bidability": data.bidability,
  };

}